### ISSUE TITLE
Porcelain.spawn does not send result message with exit status

### ISSUE THREAD

**Issue by vitaliel** [alco/porcelain#15]
I use goon driver,
```elixir
defmodule Breakout.Exec do
  def start(cmd, args) do
    pid = spawn fn -> init(cmd, args) end
    {:ok, pid}
  end

  def init(cmd, args) do
    options = [in: :receive, out: {:send, self}, err: {:send, self}]
    process = Porcelain.spawn(cmd, args, options)
    state = %{proc: process}
    loop(state)
  end

  def loop(state) do
    receive do
      {_from, :data, :out, data} ->
        IO.puts "out: #{inspect data}"
      {_from, :data, :err, data} ->
        IO.puts "err: #{inspect data}"
      msg ->
        IO.puts "unexpected msg: #{inspect msg}"
    end

    IO.puts "loop: #{inspect state}"
    loop(state)
  end
end
```

But I do not receive :result message with exit status.
```
iex(1)> Breakout.Exec.start "echo", ["1234"]
{:ok, #PID<0.136.0>}
out: "1234\n"
loop: %{proc: %Porcelain.Process{err: {:send, #PID<0.136.0>}, out: {:send, #PID<0.136.0>}, pid: #PID<0.138.0>}}
```

I can not know when to stop the receive loop. What am I doing wrong?

**Comment by alco** [comment]
Hm, might be a bug in `goon` where it keeps the input pipe open and doesn't detect that the `echo` process is already gone.

In any case, since you specify `in: :receive` when spawning a process, you need to send it an EOF at some point to close the input pipe, like this

```elixir
options = [in: :receive, out: {:send, self}, err: {:send, self}]
process = Porcelain.spawn(cmd, args, options)
# ...

# close the input pipe
Porcelain.Process.send_input(process, "")
```

The will let the spawned OS process to process the input and once it terminates, you will get back the `:result` message. See http://porcelain.readthedocs.org/en/v2.0/index.html#Porcelain.Process.send_input/2 for more info.

If you have all of your input upfront, you can pass it directly into the `:in` option, then you won't need to call `Porcelain.Process.send_input` and you'll get back a `:result` message as soon as the OS process terminates.

**Comment by vitaliel** [comment]
thanks.
